data:
  query_file_paths:
    - "https://raw.githubusercontent.com/THUNLP-MT/StableToolBench/refs/heads/master/solvable_queries/test_instruction/G1_category.json"
    - "https://raw.githubusercontent.com/THUNLP-MT/StableToolBench/refs/heads/master/solvable_queries/test_instruction/G1_instruction.json"
    - "https://raw.githubusercontent.com/THUNLP-MT/StableToolBench/refs/heads/master/solvable_queries/test_instruction/G1_tool.json"
  fine_tuning_query_file_paths:
    - "https://raw.githubusercontent.com/THUNLP-MT/StableToolBench/refs/heads/master/solvable_queries/test_instruction/G2_category.json"
    - "https://raw.githubusercontent.com/THUNLP-MT/StableToolBench/refs/heads/master/solvable_queries/test_instruction/G2_instruction.json"
    - "https://raw.githubusercontent.com/THUNLP-MT/StableToolBench/refs/heads/master/solvable_queries/test_instruction/G3_instruction.json"
  tool_file_paths:
    - "https://huggingface.co/datasets/stabletoolbench/ToolEnv2404/resolve/main/toolenv2404_filtered.tar.gz"
  reference_answers_path: "https://huggingface.co/datasets/stabletoolbench/baselines/resolve/main/data_baselines.zip"
  reference_model_id: "chatgpt_cot"
  queries_num: null
  additional_examples_model_id: "Qwen/Qwen3-8B"
  generate_examples: False

models:
  - id: "Qwen/Qwen3-8B"
    url: "${QWEN_MODEL_URL}"
    provider_id: "vllm"
  - id: "granite32-8b"
    url: "${GRANITE_MODEL_URL}"
    provider_id: "vllm"
  - id: "llama32-3b"
    url: "${LLAMA_32_MODEL_URL}"
    provider_id: "vllm"
  - id: "llama-3.1-8B"
    url: "${LLAMA_31_MODEL_URL}"
    provider_id: "ollama"
  - id: "AtlaAI/Selene-1-Mini-Llama-3.1-8B"
    url: "${SELENE_JUDGE_MODEL_URL}"
    provider_id: "vllm"

environments:
  - model_id: "Qwen/Qwen3-8B"
    irrelevant_tools_ratio: 0.0
    irrelevant_tools_from_same_categories: true

algorithms:
  - label: "Baseline"
    module_name: "baseline_algorithm"
    settings:
      available_tools_per_query: null
  - label: "Baseline Tool RAG"
    module_name: "tool_rag"
    settings:
      top_k: 10 # default
  - label: "Top-15 Tools"
    module_name: "tool_rag"
    settings:
      top_k: 15
  - label: "Top-20 Tools"
    module_name: "tool_rag"
    settings:
      top_k: 20
  - label: "E5 Embedding"
    module_name: "tool_rag"
    settings:
      embedding_model_id: "intfloat/e5-large-v2"
  - label: "BGE Embedding"
    module_name: "tool_rag"
    settings:
      embedding_model_id: "BAAI/bge-large-en-v1.5"
  - label: "Index Tools By Name Alone"
    module_name: "tool_rag"
    settings:
      indexed_tool_def_parts: ["name"]
  - label: "Index Tools By Description Alone"
    module_name: "tool_rag"
    settings:
      indexed_tool_def_parts: ["description"]
  - label: "Index Tools By Name and Args"
    module_name: "tool_rag"
    settings:
      indexed_tool_def_parts: ["name", "args"]
  - label: "Index Tools By Description and Args"
    module_name: "tool_rag"
    settings:
      indexed_tool_def_parts: ["description", "args"]
  - label: "Index Tools By Name, Description and Args"
    module_name: "tool_rag"
    settings:
      indexed_tool_def_parts: ["name", "description", "args"]
  - label: "Text and Query Preprocessing On"
    module_name: "tool_rag"
    settings:
      text_preprocessing_operations: "all"
  - label: "Tool Text Truncation On"
    module_name: "tool_rag"
    settings:
      max_document_size: 256
  - label: "Query Similarity Threshold 0.2"
    module_name: "tool_rag"
    settings:
      tau: 0.2
  - label: "Query Similarity Threshold 0.3"
    module_name: "tool_rag"
    settings:
      tau: 0.3
  - label: "Diversity Threshold 0.9"
    module_name: "tool_rag"
    settings:
      sim_threshold: 0.9
  - label: "Diversity Threshold 0.95"
    module_name: "tool_rag"
    settings:
      sim_threshold: 0.95
  - label: "Hybrid Search"
    module_name: "tool_rag"
    settings:
      hybrid_mode: true
  - label: "Reranking"
    module_name: "tool_rag"
    settings:
      cross_encoder_model_name: "BAAI/bge-reranker-large"
  - label: "Query Rewriting"
    module_name: "tool_rag"
    settings:
      enable_query_rewriting: true
  - label: "Query Decomposition"
    module_name: "tool_rag"
    settings:
      enable_query_decomposition: true

metric_collectors:
  - module_name: "answer_quality_metric_collector"
    settings:
      judges:
        # task_success_no_ref: "llama32-3b"
        task_success_with_ref: "Qwen/Qwen3-8B"
  - module_name: "fac_metric_collector"
    settings: {}
  - module_name: "tool_selection_metric_collector"
    settings: {}
  - module_name: "tool_retrieval_metric_collector"
    settings:
      ks: [1, 3, 5]
      ap_rel_threshold: 1.0
  - module_name: "efficiency_metric_collector"
    settings: {}
